name: Build HTML on merge
on:
  pull_request:
   branches:
   - main
   types: [closed]

  workflow_dispatch:

permissions:
  contents: write
  id-token: write
  

jobs:
  Generate_HTML:
    if: github.event.pull_request.merged == true
    uses: spacetelescope/notebook-ci-actions/.github/workflows/ci_builder.yml@gough_test
    with:
      python-version: ${{ vars.PYTHON_VERSION }}
