name: Build HTML on merge

on:
  pull_request:
    types: [closed]
    paths:
      - '**.ipynb'

env:
  CASJOBS_PW: ${{ secrets.CASJOBS_PW }}
  CASJOBS_USERID: ${{ secrets.CASJOBS_USERID }}
jobs:
  prepare_matrix:
    #if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    outputs:
      matrix: ${{ steps.set-matrix.outputs.matrix }}
    steps:
      - uses: actions/checkout@v3
        with:
          ref: ${{ github.event.pull_request.head.sha }}

      - id: set-matrix
        run: |
          files=$(git diff --name-only ${{ github.event.pull_request.base.sha }}...${{ github.event.pull_request.head.sha }} '*.ipynb')
          files_json=$(echo $files | jq -R -s -c 'split("\n")[:-1]')
          echo "::set-output name=matrix::${files_json}"

  execute-notebooks:
    needs: prepare_matrix
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        notebook: ${{fromJson(needs.prepare_matrix.outputs.matrix)}}
    steps:
      - uses: actions/checkout@v3

      - name: Setup Python
        uses: actions/setup-python@v3
        with:
          python-version: '3.x'

      - name: Install Dependencies (if requirements.txt exists) and Execute Notebook
        run: |
          notebook="${{ matrix.notebook }}"
          dir=$(dirname "$notebook")
          if [ -f "$dir/requirements.txt" ]; then
            pip install -r "$dir/requirements.txt"
          fi
          pip install notebook
          jupyter nbconvert --to notebook --execute "$notebook" --inplace
          git add "$notebook"
          git commit -m "Execute notebooks"
          git push origin HEAD:gh-storage --force


  generate_html:
    #if: github.event.pull_request.merged == true
    needs: execute-notebooks
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
    - name: Checkout repository
      uses: actions/checkout@v4

    - name: Set up Python ${{ vars.python-version }}
      uses: actions/setup-python@v5
      with:
        python-version: ${{ vars.python-version }}
        
    - name: Install dependencies
      run: |
        pip install ghp-import
        pip install jupyter-book==v0.15.1
        pip install myst-nb
        pip install astroid
        pip install nbval
        #pip install bs4
        #pip install lxml
        ## test to bypass the jupyter-book lower version
        pip install jsonschema==4.6.0
        PATH="${PATH}:${HOME}/.local/bin"

    - name: Build HTML
      run: |
        git fetch
        git checkout origin/gh-storage -- notebooks/
        jupyter-book build .

    # Push the book's HTML to github-pages
    - name: GitHub Pages action
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./_build/html
