## Workflow to run when there is a direct push to the main branch, or a PR is submitted.
## The workflow runs three workflows - Valdation, Execution, and HTML Deployment.
## The jobs are dependent on the previous succeding - if valdiation fails, the rest will, if 
## execution fails, html deployment will not run.
## Each job runs on its own runner with an independent environment, with the exception of the 
## HTML generation, which occurs on a single runner using the global environment.

name: Notebook Execution and Validation

on:
  pull_request:
    branches:
      - main
    paths:
      - 'notebooks/**.ipynb'
      - '*.yml'

permissions:
  contents: write
  id-token: write
  issues: write
  pull-requests: write

jobs:
  check-pr-source:
    runs-on: ubuntu-latest
    outputs:
      is_fork: ${{ steps.fork-check.outputs.is_fork }}
    steps:
      - name: Check if PR is from a fork
        id: fork-check
        run: |
          echo "PR_BASE_REPO: ${{ github.event.pull_request.base.repo.full_name }}"
          echo "PR_HEAD_REPO: ${{ github.event.pull_request.head.repo.full_name }}"
          if [ "${{ github.event.pull_request.base.repo.full_name }}" != "${{ github.event.pull_request.head.repo.full_name }}" ]; then
            echo "::set-output name=is_fork::true"
          else
            echo "::set-output name=is_fork::false"
          fi

  NotebookExecutionValidation:
    needs: check-pr-source
    if: needs.check-pr-source.outputs.is_fork == 'false'
    uses: spacetelescope/notebook-ci-actions/.github/workflows/ci_runner.yml@gough_test
    with:
      python-version: ${{ vars.PYTHON_VERSION }}
    secrets:
      CASJOBS_PW: ${{ secrets.CASJOBS_PW }}
      CASJOBS_USERID: ${{ secrets.CASJOBS_USERID }}
      CITOKEN: ${{ secrets.CITOKEN }}
    permissions:
      contents: write
