## Workflow to run when there is a direct push to the main branch, or a PR is submitted.
## The workflow runs three workflows - Valdation, Execution, and HTML Deployment.
## The jobs are dependent on the previous succeding - if valdiation fails, the rest will, if 
## execution fails, html deployment will not run.
## Each job runs on its own runner with an independent environment, with the exception of the 
## HTML generation, which occurs on a single runner using the global environment.

name: Notebook Execution and Validation

on:
  pull_request:
    branches:
      - main
    paths:
      - 'notebooks/**.ipynb'
      - '*.yml'

permissions:
  contents: write
  id-token: write
  issues: write
  pull-requests: write

jobs:
  check-pr-source:
    runs-on: ubuntu-latest
    outputs:
      is_fork: ${{ steps.fork-check.outputs.is_fork }}
    steps:
      - name: Check if PR is from a fork
        id: fork-check
        run: |
          if [ "${{ github.event.pull_request.base.repo.full_name }}" != "${{ github.event.pull_request.head.repo.full_name }}" ]; then
            echo "::set-output name=is_fork::true"
          else
            echo "::set-output name=is_fork::false"
          fi

  handle-fork-pr:
    needs: check-pr-source
    if: needs.check-pr-source.outputs.is_fork == 'true'
    runs-on: ubuntu-latest
    steps:
      - name: Checkout base repo main branch
        uses: actions/checkout@v3
        with:
          ref: main
          fetch-depth: 0

      - name: Set up Git with CITOKEN and push changes
        env:
          CITOKEN: ${{ secrets.CITOKEN }}  # Ensure this matches your secret name
        run: |
          NEW_BRANCH="fork-pr-${{ github.event.pull_request.number }}"
          git config --global user.email "action@github.com"
          git config --global user.name "GitHub Action"
          
          # Correctly format the URL to include the CITOKEN for authentication
          git remote set-url origin https://x-access-token:${CITOKEN}@github.com/${{ github.repository }}
          
          git checkout -b $NEW_BRANCH main
          git pull --no-rebase origin main
          git push origin $NEW_BRANCH

      - name: Create new PR to main from the new branch
        uses: actions/github-script@v6
        with:
          script: |
            const originalDescription = `${{ github.event.pull_request.body }}\n\nOriginal PR: #${{ github.event.pull_request.number }}`;
            const pullRequest = await github.rest.pulls.create({
              owner: context.repo.owner,
              repo: context.repo.repo,
              title: 'New PR for Changes from Fork: ${{ github.event.pull_request.title }}',
              head: '${{ env.NEW_BRANCH }}',
              base: 'main',
              body: originalDescription,
              draft: false,
            });
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NEW_BRANCH: fork-pr-${{ github.event.pull_request.number }}


  NotebookExecutionValidation:
    needs: check-pr-source
    if: needs.check-pr-source.outputs.is_fork == 'false'
    uses: spacetelescope/notebook-ci-actions/.github/workflows/ci_runner.yml@gough_test
    with:
      python-version: ${{ vars.PYTHON_VERSION }}
    secrets:
      CASJOBS_PW: ${{ secrets.CASJOBS_PW }}
      CASJOBS_USERID: ${{ secrets.CASJOBS_USERID }}
      CITOKEN: ${{ secrets.CITOKEN }}
    permissions:
      contents: write
